#

# NOTE(jkoelker) Get as many dependancies from official docker images to allow
#                `dependabot` to bump them
FROM docker.io/golangci/golangci-lint:v1.52.2-alpine as golangci-lint
FROM docker.io/hadolint/hadolint:v2.12.0-alpine as hadolint

FROM docker.io/golang:1.20.4-alpine as builder

# NOTE(jkoelker) install the tools in the builder here to improve layer
#                caching of the published devkit.
ENV GOBIN=/tools
COPY tools /go/src/github.com/lazygpt/lazygtp/
WORKDIR /go/src/github.com/lazygpt/lazygtp

# NOTE(jkoelker) We want word splitting for the output of `go list`
# hadolint ignore=SC2046
RUN mkdir -p /tools \
    && go install -v $(go list -f '{{ join .Imports " " }}' -tags=tools)

# NOTE(jkoelker) From here we care about layers
FROM docker.io/golang:1.20.4-alpine

# NOTE(jkoelker) Ignore "Pin versions in apk add"
# hadolint ignore=DL3018
RUN apk add --no-cache \
        bash \
        gcc \
        git \
        libc-dev \
        protoc \
        make

COPY --from=hadolint /bin/hadolint /usr/local/bin/
COPY --from=golangci-lint /usr/bin/golangci-lint /usr/local/bin/
COPY --from=builder /tools /usr/local/bin

CMD ["/bin/bash"]
